name: "Nix Copy to Cache"
description: "GitHub Action to copy Nix derivations to a specified cache."

inputs:
  result:
    description: "The Nix build result to be copied."
    required: true
  conn:
    description: "The remote store connection string for the Nix cache."
    required: true

runs:
  using: "composite"
  steps:
    - name: Copy Nix store to cache
      run: |
        CACHE_SSH_CONN="${{ inputs.conn }}"
        RESULT="${{ inputs.result }}"

        nix copy --to "$CACHE_SSH_CONN" \
          $(nix-store -q --requisites $(nix-store -q --deriver "$RESULT")) \
          $(nix-store -q --references $(nix-store -q --deriver "$RESULT")) \
          $(nix-store -qR "$RESULT")
      shell: bash
